// @flow

// Volunteer form actions
export const VOLUNTEER_UPDATE_NAME = 'VOLUNTEER_UPDATE_NAME'
export const VOLUNTEER_UPDATE_EMAIL = 'VOLUNTEER_UPDATE_EMAIL'
export const VOLUNTEER_SUBMIT_FORM = 'VOLUNTEER_SUBMIT_FORM'
export const VOLUNTEER_SUBMIT_FORM_SUCCESS = 'VOLUNTEER_SUBMIT_FORM_SUCCESS'
export const VOLUNTEER_SUBMIT_FORM_ERROR = 'VOLUNTEER_SUBMIT_FORM_ERROR'
